#!/bin/sh
battery="$(acpi | awk -F ' ' 'END {print $4}' | tr -d \%,)"
charge="$(acpi | awk -F ' ' 'END {print $3}' | tr -d \,)"

if [[ $1 == "icon" ]]; then
   if [[ ($charge = *"Charging"*) && ($battery -lt "100") ]]; then
      echo "󰂄"
   elif [[ $charge = *"Full"* ]]; then
      echo "󰁹"
   else
      if [[ ($battery -lt 100) && (($battery -gt 65) || ($battery -eq 65)) ]]; then
         echo "󰂂"
      elif [[ ($battery -lt 65) && (($battery -gt 35) || ($battery -eq 35)) ]]; then
         echo "󰂀"
      elif [[ ($battery -lt 35) && (($battery -gt 10) || ($battery -eq 10)) ]]; then
         echo "󰁼"
      else
         echo "󱃍"
      fi
   fi
fi

if [[ $1 == "percent" ]]; then
   echo $battery
fi