#!/bin/sh
battery="$(acpi | awk -F ' ' 'END {print $4}' | tr -d \%,)"
charge="$(acpi | awk -F ' ' 'END {print $3}' | tr -d \,)"

if [[ ($charge = *"Charging"*) && ($battery -lt "100") ]]; then
   export icon="󰂄"
elif [[ $charge = *"Full"* ]]; then
   export icon="󰁹"
else
   if [[ ($battery -lt 100) && (($battery -gt 65) || ($battery -eq 65)) ]]; then
      export icon="󰂂"
   elif [[ ($battery -lt 65) && (($battery -gt 35) || ($battery -eq 35)) ]]; then
      export icon="󰂀"
   elif [[ ($battery -lt 35) && (($battery -gt 10) || ($battery -eq 10)) ]]; then
      export icon="󰁼"
   else
      export icon="󱃍"
   fi
fi

echo $icon,$battery
