#!/bin/sh
if [[ $1 == "icon" ]]; then
   if [[ $(cat /sys/class/net/w*/operstate) = down ]]; then
      echo "󰤭"
   else
      echo "󰤨"
   fi
fi

if [[ $1 == "name" ]]; then
   echo $(nmcli | grep "^wlo1" | sed -e 's,.*connected to \(.*\),\1,')
fi
