#! /bin/bash
icons=(一 二 三 四 五 六 七 八 九 〇)

for row in $(echo $(hyprctl workspaces -j) | jq -r '.[] | @base64'); do
   c=$(echo $row | base64 --decode | jq -r ${1})
   num=$(echo $c | jq '.id')
   monitor=$(echo $c | jq -r '.monitor')
   monitor="${monitor//-/_}"

   export s"$num"="occupied"
   export mo"$num"="$monitor"
done

for row in $(echo $(hyprctl monitors -j) | jq -r '.[] | @base64'); do
   c=$(echo $row | base64 --decode | jq -r ${1})
   monitor=$(echo $c | jq -r '.name')
   monitor="${monitor//-/_}"
   num=$(echo $c | jq '.activeWorkspace.id')
   focused=$(echo $c | jq -r '.focused')

   if [[ $focused == "true" ]]; then
      export fm="$monitor"
   fi
   
   export s"$num"="focused_$monitor"
   export fw"$monitor"="$num"
done

echo $fm

workspaces() {
   if [[ ${1:0:16} == "destroyworkspace" ]]; then
      changed=1
      num="${1:18}"

      unset -v s"$num"
   fi

   if [[ ${1:0:10} == "focusedmon" ]]; then
      changed=1
      monitor=$(echo ${1:10} | cut -d "," -f 2)
      monitor="${monitor//-/_}"

      export fm="$monitor"
   fi

   if [[ ${1:0:15} == "createworkspace" ]]; then
      changed=1
      num="${1:17}"
      temp="s$num"

      if [[ ${!temp} != focused* ]]; then
         export s"$num"="occupied"
      fi
      
      export mo"$num"="$fm"
   fi
   
   if [[ ${1:0:9} == "workspace" ]]; then
      changed=1
      num="${1:11}"
      temp="mo${num}"
      monitor="${!temp}"
      temp=fw"$monitor" 
      last="${!temp}"

      export s"$last"="occupied"
      export fw"$monitor"="$num"
      export s"$num"="focused_$monitor"
   fi

   if [[ ${1:0:13} == "moveworkspace" ]]; then
      changed=1
      num=$(echo ${1:13} | cut -d "," -f 1)
      monitor=$(echo ${1:13} | cut -d "," -f 2)
      monitor="${monitor//-/_}"

      export mo"$num"=$monitor
   fi

   [ $changed == "1" ] && echo \
      "(eventbox :onscroll \"echo {} | sed -e 's/up/-1/g' -e 's/down/+1/g' | xargs hyprctl dispatch workspace\" \
         (box :class \"workspaces\" :orientation \"h\" :spacing 5 \
            (button :onclick \"hyprctl dispatch workspace 1\"  :class \"workspace ${s1-unoccupied}\" \"${icons[0]}\") \
            (button :onclick \"hyprctl dispatch workspace 2\"  :class \"workspace ${s2-unoccupied}\" \"${icons[1]}\") \
            (button :onclick \"hyprctl dispatch workspace 3\"  :class \"workspace ${s3-unoccupied}\" \"${icons[2]}\") \
            (button :onclick \"hyprctl dispatch workspace 4\"  :class \"workspace ${s4-unoccupied}\" \"${icons[3]}\") \
            (button :onclick \"hyprctl dispatch workspace 5\"  :class \"workspace ${s5-unoccupied}\" \"${icons[4]}\") \
            (button :onclick \"hyprctl dispatch workspace 6\"  :class \"workspace ${s6-unoccupied}\" \"${icons[5]}\") \
            (button :onclick \"hyprctl dispatch workspace 7\"  :class \"workspace ${s7-unoccupied}\" \"${icons[6]}\") \
            (button :onclick \"hyprctl dispatch workspace 8\"  :class \"workspace ${s8-unoccupied}\" \"${icons[7]}\") \
            (button :onclick \"hyprctl dispatch workspace 9\"  :class \"workspace ${s9-unoccupied}\" \"${icons[8]}\") \
            (button :onclick \"hyprctl dispatch workspace 10\" :class \"workspace ${s10-unoccupied}\" \"${icons[9]}\") \
         ) \
      )"
}

changed=1
workspaces

socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | 
   while read -r event; do
      changed=0 
      workspaces "$event"
   done