#! /bin/bash
icons=(一 二 三 四 五 六 七 八 九 〇)

for num in $(hyprctl workspaces | grep ID | sed 's/()/(1)/g' | awk 'NR>1{print $1}' RS='(' FS=')'); do
  export state"$num"="occupied"
done

for num in $(hyprctl monitors | grep active | sed 's/()/(1)/g' | awk 'NR>1{print $1}' RS='(' FS=')'); do
  export state"$num"="focused"
  export focused_workspace="$num"
done

workspaces() {
   if [[ ${1:0:16} == "destroyworkspace" ]]; then
      unset -v state"${1:18}"
   fi

   if [[ ${1:0:15} == "createworkspace" && ${1:11} -ne "focused" ]]; then
      export state"${1:17}"="occupied"
   fi
   
   if [[ ${1:0:9} == "workspace" ]]; then
      export state"$focused_workspace"="occupied"
      export focused_workspace="${1:11}"
      export state"${1:11}"="focused"
   fi

   echo \
      "(eventbox :onscroll \"echo {} | sed -e 's/up/-1/g' -e 's/down/+1/g' | xargs hyprctl dispatch workspace\" \
         (box :class \"workspaces\" :orientation \"h\" :spacing 5 \
            (button :onclick \"hyprctl dispatch workspace 1\"  :class \"workspace ${state1-unoccupied}\" \"${icons[0]}\") \
            (button :onclick \"hyprctl dispatch workspace 2\"  :class \"workspace ${state2-unoccupied}\" \"${icons[1]}\") \
            (button :onclick \"hyprctl dispatch workspace 3\"  :class \"workspace ${state3-unoccupied}\" \"${icons[2]}\") \
            (button :onclick \"hyprctl dispatch workspace 4\"  :class \"workspace ${state4-unoccupied}\" \"${icons[3]}\") \
            (button :onclick \"hyprctl dispatch workspace 5\"  :class \"workspace ${state5-unoccupied}\" \"${icons[4]}\") \
            (button :onclick \"hyprctl dispatch workspace 6\"  :class \"workspace ${state6-unoccupied}\" \"${icons[5]}\") \
            (button :onclick \"hyprctl dispatch workspace 7\"  :class \"workspace ${state7-unoccupied}\" \"${icons[6]}\") \
            (button :onclick \"hyprctl dispatch workspace 8\"  :class \"workspace ${state8-unoccupied}\" \"${icons[7]}\") \
            (button :onclick \"hyprctl dispatch workspace 9\"  :class \"workspace ${state9-unoccupied}\" \"${icons[8]}\") \
            (button :onclick \"hyprctl dispatch workspace 10\" :class \"workspace ${state10-unoccupied}\" \"${icons[9]}\") \
         ) \
      )"
}

workspaces

socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | 
   while read -r event; do 
      workspaces "$event"
   done